---
driver:
  name: vagrant

platforms:
  - name: ubuntu-16.04
    run_list:
    - recipe[apt]
    - recipe[kindlyops-base::default]

# default values: https://github.com/test-kitchen/test-kitchen/blob/master/lib/kitchen/provisioner/chef_base.rb#L183-L190
provisioner:
  name: chef_zero
  require_chef_omnibus: 12.19.36
  data_bags_path: 'data_bags'
  #encrypted_data_bag_secret_key_path: <%= ENV['KITCHEN_DATA_BAG_SECRET_PATH'] || '.encrypted_data_bag_secret' %>
  attributes:
    gritstone:
      firewall: false
      kitchen: true
    firewall:
      allow_ssh: true
    ssh-hardening:
      ssh:
        ports:
          - 22
          - 2222
        server:
          max_auth_tries: 4 # needed for test-kitchen to try different keys
    public_info:
      remote_ip: '127.0.0.1'
    cloud:
      public_ipv4: '127.0.0.1'
    authorization:
      sudo:
        users: ['vagrant','kitchen']
        passwordless: true
    disk:
      timeout: 10
    testkitchen: true
    network:
      interfaces:
        eth1:
          addresses:
            127.0.0.1:
              family: 'inet'

suites:
  - name: default
    run_list:
      - recipe[kindlyops-base::default]
